### ISSUE TITLE
Feature Request - Allow downloading by tag version

### ISSUE THREAD

**Issue by dakota-maker-by** [dsaltares/fetch-gh-release-asset#12]
Hi there,

I was trying to use your action for my team to download a tar file from some of our other repos, but we are going to do it by specifying the repo and the tag version of a particular tar file. I know this can be done by hitting `$API_URL/releases/tags/${VERSION OF TAR}` for the release data, so it would be nice to leverage an action instead of having to do these commands in our workflow itself.

Just a suggestion, and if nothing else I would be happy to try and add a contrib to the repo.

Thank you

**Comment by dsaltares** [comment]
Hi @dakota-maker-by, thanks for submitting this. I agree that could be useful. Unfortunately, I don't have the capacity at the moment to implement this. However, I would be more than happy to review a PR that implements this! 🙌 .

**Comment by damian-bisignano** [comment]
This has broken something. we're getting an error that the Release asset is not found now (also private repos).

I've fixed my problem by just referencing the old commit hash directly

**Comment by henriquelbsouza** [comment]
![image](https://user-images.githubusercontent.com/1070818/120664027-f5857200-c460-11eb-81c9-572c6cadd727.png)

It broke something for us as well... Is there something I am missing?

It just stopped working on @master :/
`
name: Download release and upload to Chrome Store
on:
 workflow_dispatch:
 release:
    types:
      - published
      - created
      - edited
      - released
jobs:
  publish:
    name: Release to Chrome Store
    runs-on: ubuntu-latest
    steps:
      - name: Download Github release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "gamersclub-booster/gamersclub-booster"
          version: "latest"
          file: "release.zip"
          target: "release.zip"
          token: ${{ secrets.YOUR_TOKEN }}

      - name: Upload to Chrome Store
        uses: Klemensas/chrome-extension-upload-action@master
        with:
          app-id: ${{ secrets.CHROME_STORE_APP_ID }}
          refresh-token: ${{ secrets.CHROME_STORE_REFRESH_TOKEN }}
          client-id: ${{ secrets.CHROME_STORE_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_STORE_CLIENT_SECRET }}
          file-name: "./release.zip"
          publish: true
`

**Comment by Auze** [comment]
I confirm this actions does not work anymore. 
Trying to download a release by tag and I have the same error. 

```
      - name: test
        uses: dsaltares/fetch-gh-release-asset@0.0.5
        with:
          #repo: "dsaltares/godot-wild-jam-18"
          version: "tags/v1.6.0"
          file: "v1.6.0.zip"
          target: "infrastucture/terraform/lambda-function.zip"
          token: ${{ secrets.TOKEN_GITHUB }}
```
