### ISSUE TITLE
My github action stopped working today

### ISSUE THREAD

**Issue by azagaya** [dsaltares/fetch-gh-release-asset#18]
Hi! I'm not sure if this is an issue or a problem on my side (most probably). But I've been using this with github actions to push my game to itch.io... And today it suddenly stopped working, perhaps related to #17 ?
I think this is the relevant part of the action:

```
  release_html:
    runs-on: ubuntu-latest
    steps:
      - name: HTML
        id: html
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: "HTML5.zip"
        env:
          GITHUB_TOKEN: "${{ secrets.GH_CREDENTIALS }}"

```
I can post the complete action if needed. Is this supposed to work? because it was working until yesterday. Now I'm getting this>

```
[!] Release asset not found
Release data: {
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/reference/repos#get-the-latest-release"
}
-----
```
Maybe someone can help me get it working again? thanks in advance
