### ISSUE TITLE
Example from README does not work

### ISSUE THREAD

**Issue by priya2811-khatri** [dsaltares/fetch-gh-release-asset#5]
I tried to fetch an assets from another repo by using the Readme Example.
```
uses: dsaltares/fetch-gh-release-asset@master
with:
  repo: “Organisation/Repo”
  version: "latest"
  file: "asset_01.zip"
  token: ${{ secrets.MY_TOKEN }}
```
Job failed with an error of `Missing GITHUB_TOKEN env variable`.

Then I tried with following method:
```
uses: dsaltares/fetch-gh-release-asset@master
       env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
       with:
        repo: "Organisation/Repo"
        version: "latest"
        file: "asset_01.zip"
        token: ${{ env.GITHUB_TOKEN }}
```
And it worked.
